### ISSUE TITLE
Purpose of this project

### ISSUE THREAD

**Issue by Daveiano** [stellitecoin/xtl-nodejs-pool#12]
I really don't know if this a dumb question, or if I misunderstand something, but:

I can run a XTL Pool also with the [original project](https://github.com/dvandal/cryptonote-nodejs-pool) which this was forked from, right?

So what is the purpose of this project, why should I choose it? Which are the differences?

**Comment by ahmyi** [comment]
This pool is only dedicated to XTL only..we dont cater other coins. Such improvements are:

- integrations with stellitepay
- cater mobile mining improvements
- contributions to developers via donations ( default contribution is set towards dev address)
- any un foreseen bugs of mining for this coins

**Comment by Daveiano** [comment]
Ok, I understand. So this is an optimized version of the node-pool just for XTL. And finally this pool supports a current NodeJS version :)
