### ISSUE TITLE
Payout levels cannot be set.

### ISSUE THREAD

**Issue by unsivilaudio** [stellitecoin/xtl-nodejs-pool#15]
Muddling through the frontend script, I've narrowed it down to after correcting this line to;
`var address = $('#yourStatsInput').val().trim();`

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://stellite.ethospool.org:8117"

EDIT: The plot thickens...Just noticed my pool throwing this error when attempting to set payout level.
http://prntscr.com/m8mwo8

**Comment by ahmyi** [comment]
[Fix](https://github.com/stellitecoin/xtl-nodejs-pool/tree/v1.4.7)

**Comment by unsivilaudio** [comment]
Beautiful.  Thank you.
