### ISSUE TITLE
Installing the hashing update for the [V9] fork breaks the pool.

### ISSUE THREAD

**Issue by unsivilaudio** [stellitecoin/xtl-nodejs-pool#16]
Installing the latest MoneroOcean code for node-cryptonight-hashing module, breaks this pool.  All shares will be malformed.  The downside to not installing this, is, the only miner that can mine on this pool after the fork is xtl-stak, due to some issue of algo detection(?).

https://github.com/MoneroOcean/node-cryptonight-hashing

**Comment by ahmyi** [comment]
For [xmr-stak](https://github.com/fireice-uk/xmr-stak/issues/2172) on cn/half algo. If not mistaken thats what they call it. So for now only xtl-stak.

**Comment by ahmyi** [comment]
Ok i change variant to cn/half something i missed out.. thanks for mentioning

**Comment by unsivilaudio** [comment]
Fixed,  Thank you very much!

You sir, are a rockstar.  I didn't see it anywhere, do you have a donations address?
