### ISSUE TITLE
Help me config the web

### ISSUE THREAD

**Issue by nthon** [stellitecoin/xtl-nodejs-pool#3]
Hi there,

My pool run ok but the web cannot connect to the pool, how I fix it?

thanks

**Comment by hayzamjs** [comment]
Please give us more information.

**Comment by nthon** [comment]
Now I am rebuilding my pool, when it finished, I will give more about it. Thank you very much!

**Comment by nthon** [comment]
Hi, I finded how to fix it. Thankful.
